### ISSUE TITLE
Front-end need love

### ISSUE THREAD

**Issue by flexbox** [lewagon/rails-kickoff#1]
Hello here cc @Papillard ,

What do you think to drop this 

```
gem 'bootstrap-sass'
```

And add this 

```
gem 'foundation'
gem 'slim'
```
### Why ?

Foundation work great with Sass, bootstrap is write in less. (There is a cli to build the sass version but it's another level of abstraction).
That's it.

`slim` allow front-end dev to work 2x faster because it drop the close tag nightmare.

If you agree with this i will make a PR, if not simply clode the issue :smile:

**Comment by ssaunier** [comment]
Hi David, thanks for this issue, BTW how did you discover this repo ? :)

Well, your suggestions are very _à propos_, but I'm afraid we won't integrate them for this rails-kickoff project, let me explain why:
- _Audience_: This Kick-Off has been created primary for the need of the [FullStack bootcamp](http://www.lewagon.org/program) of Le wagon.
- Foundation: the sass port of Bootstrap works very well, in the end we don't really care how Bootstrap is built as we don't hack on it, we juste the [variables](http://getbootstrap.com/customize/). From my experience Bootstrap has more users & plugins (date pickers, etc...) than Foundation, so we went down this path.
- _Slim_: I know that `erb` is very verbose and `slim` fixes that (although I don't really agree with you on the fact that there is a linear correlation between the number of lines of code written by the Front-End developer and its productivity ;) ), but what I like about it is that it's very close from HTML. In this case, the abstraction (from HTML) that `slim` forces us to use is, IMHO, too much for the students. In 9 weeks, they discovered the terminal, git, Ruby, SQL, HTML, CSS, JavaScript, and Rails to glue all that stuff. I think that one more syntax would be a bit much. Of course, once they've internalized these concepts and are at ease, they could switch to `slim`

Thanks for your issue, I hope this discussion would bring some insights for others.

Cheers!

**Comment by flexbox** [comment]
> how did you discover this repo ?

Ask to @cveneziani the next time you see her :)

**Comment by ssaunier** [comment]
Hehe, will do on monday, thanks!
